export default {
  SET_CREATE_DATA: 'PAYMENT_SET_CREATE_DATA',
  CLEAR_CREATE_DATA: 'PAYMENT_CLEAR_CREATE_DATA',

  CREATE_PAYMENT: 'API:PAYMENT_CREATE',
  CREATE_PAYMENT_SUCCESS: 'PAYMENT_CREATE_SUCCESS',
  CREATE_PAYMENT_FAILURE: 'PAYMENT_CREATE_FAILURE',

  GET_STATUSES: 'API:PAYMENT_GET_STASUSES',
  GET_STATUSES_SUCCESS: 'PAYMENT_GET_STASUSES_SUCCESS',
  GET_STATUSES_FAILURE: 'PAYMENT_GET_STASUSES_FAILURE',

  GET_PAYMENTS: 'API:PAYMENTS_GET',
  GET_PAYMENTS_SUCCESS: 'PAYMENTS_GET_SUCCESS',
  GET_PAYMENTS_FAILURE: 'PAYMENTS_GET_FAILURE',

  SET_FILTER_DATA: 'PAYMENT_SET_FILTER_DATA',

  SET_SORTING: 'PAYMENT_SET_SORTING',
}
