export default {
  SIGN_IN: 'SERVER:LOGIN',
  SIGN_IN_ERROR: 'LOGIN_ERROR',
  SIGN_IN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT: 'LOGOUT',

  SET_DATA: 'AUTH_SET_DATA',

  GET_USER: 'GET_USER',

  CLEAR_AUTH: 'AUTH_CLEAR',
  CLEAR_DATA: 'AUTH_CLEAR_DATA',
}
